// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({}),
};

import * as ConsultingNewRoute from "@/app/consulting/new/page.info";
import * as ConsultingRoute from "@/app/consulting/page.info";
import * as JobsNewRoute from "@/app/jobs/new/page.info";
import * as HomeRoute from "@/app/page.info";

export const Home = makeRoute("/", {
  ...defaultInfo,
  ...HomeRoute.Route,
});
export const Consulting = makeRoute("/consulting", {
  ...defaultInfo,
  ...ConsultingRoute.Route,
});
export const ConsultingNew = makeRoute("/consulting/new", {
  ...defaultInfo,
  ...ConsultingNewRoute.Route,
});
export const JobsNew = makeRoute("/jobs/new", {
  ...defaultInfo,
  ...JobsNewRoute.Route,
});
